name: All

on:
  push:
    branches: [ "master", "dev-ci"]
    tags: "v*.*.*"
  pull_request:
    branches: [ "master" ]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  BUILD_TYPE: release
  # BUILD_TYPE: debug

jobs:
  cpp-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check code style by cpp-lint
        run: |
          sudo apt install python3
          ./script/check.sh
  
  clang-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: check code style by clang-format
        run: |
          sudo apt install clang-format
          ./script/clang_format_change.sh

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: restore ccache
        id: build
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/ccache
          key: ccache-${{ runner.os }}-${{ runner.arch }}-${{ env.BUILD_TYPE }}
          restore-keys: |
            ccache-${{ runner.os }}-${{ runner.arch }}-

      - name: build and pkg
        run: |
          ls &&
          cd ${{github.workspace}} &&
          ./script/build_static_in_docker.sh --${{ env.BUILD_TYPE }} --pkg ./output --ci --ccache-dir ./ccache &&
          tar zcf output-${{ env.BUILD_TYPE }}.tar.gz output

      - name: check output
        run: ldd ${{github.workspace}}/output/bin/main

      - name: upload collected artifact
        uses: actions/upload-artifact@v3
        with:
          name: files-${{ env.BUILD_TYPE }}
          path: ${{github.workspace}}/output-${{ env.BUILD_TYPE }}.tar.gz

      - name: gen AppImage
        run: |
          ls
          sudo chmod -R +x output/*
          sudo add-apt-repository universe
          sudo apt install -y libfuse2
          cd ${{github.workspace}}
          ./script/appimg.sh ./output

      - name: upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: AppImages-${{ env.BUILD_TYPE }}
          path: ${{github.workspace}}/OnnxEditor-*.AppImage

      - name: release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            output-${{ env.BUILD_TYPE }}.tar.gz
            ${{github.workspace}}/OnnxEditor-*.AppImage
